version: "3.3"
services:
  mango-service-v3:
    
    restart: always
    build: mango-service-v3
    ports:
      - "3000:3000"
    volumes:
      - ~/.config/solana:/root/.config/solana # mount volume where keys are present, also see PRIVATE_KEY_PATH
    environment:
      - PORT=3000
      - GROUP_NAME=mainnet.1
      - CLUSTER_URL=https://solana--mainnet.datahub.figment.io/apikey/24c64e276fc5db6ff73da2f59bac40f2
      - PRIVATE_KEY_PATH=/usr/id.json # configure path to private keypair here
  mango-bowl:
    
    restart: always
    build: "mango-bowl"
    ports:
      - "8005:8005"
    environment:
      - MB_PORT=8005
      - MB_ENDPOINT=https://solana--mainnet.datahub.figment.io/apikey/24c64e276fc5db6ff73da2f59bac40f2 # configure custom RPC node
  reverse-proxy:
    build: .
    
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf # custom config which unifies mango-service-v3 and mango-bowl
